---
- name: create file
  hosts: all
  remote_user: ec2-user

  vars:
     age: 12
  tasks:
  - name: create file
    command: touch /tmp/dummi.txt
    when: age == 10 or  age == 12

  - name: remove file
    file: dest=/tmp/dummi.txt state=absent
