---
- name: copy file
  hosts: all
  remote_user: ec2-user

  tasks:
  - name: copy file
    copy: 
      src: /home/sandeep/ansible_test/module/file.txt
      dest: /tmp/

  - name: remove file
    file:
       dest: /tmp/file.txt
       state: absent
