---
- name: start service
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: install httpd
    yum: name=httpd state=latest
    notify: 
         - restart httpd

  - name: service start
    service: name=httpd state=started

  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
